// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function Board$Tile(Props) {
  var tile = Props.tile;
  var id = Props.id;
  Props.gameStatus;
  var setMark = Props.setMark;
  var symbol = tile ? (
      tile[0] ? React.createElement("span", {
              className: "circle"
            }, "O") : React.createElement("span", {
              className: "cross"
            }, "X")
    ) : null;
  return React.createElement("div", {
              className: "item"
            }, React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setMark, id);
                    })
                }, symbol));
}

var Tile = /* module */[/* make */Board$Tile];

function Board$Row(Props) {
  var row = Props.row;
  var rowIndex = Props.rowIndex;
  var gameStatus = Props.gameStatus;
  var setMark = Props.setMark;
  return $$Array.of_list(List.mapi((function (index, tile) {
                    var id = String(rowIndex) + String(index);
                    return React.createElement(Board$Tile, {
                                tile: tile,
                                id: id,
                                gameStatus: gameStatus,
                                setMark: setMark,
                                key: String(index)
                              });
                  }), row));
}

var Row = /* module */[/* make */Board$Row];

function Board(Props) {
  var board = Props.board;
  var gameStatus = Props.gameStatus;
  var setMark = Props.setMark;
  var boardRow = $$Array.of_list(List.mapi((function (index, row) {
              return React.createElement(Board$Row, {
                          row: row,
                          rowIndex: index,
                          gameStatus: gameStatus,
                          setMark: setMark,
                          key: String(index)
                        });
            }), board));
  return React.createElement("div", {
              className: "board"
            }, boardRow);
}

var make = Board;

export {
  Tile ,
  Row ,
  make ,
  
}
/* react Not a pure module */
