// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Game$ReactHooksTemplate from "./components/Game.bs.js";

import "./index.css"
;

function App(Props) {
  return React.createElement("div", undefined, React.createElement(Game$ReactHooksTemplate.make, { }));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
